package com.worthto.ecps.model;

public class EbCat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.CAT_ID
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private Long catId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.CAT_NAME
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String catName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.CAT_DESC
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String catDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.PARENT_ID
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.CAT_SORT
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private Integer catSort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.KEYWORDS
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String keywords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.PATH
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.MARK
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String mark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.ISDISPLAY
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private Integer isdisplay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.FULL_PATH
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private String fullPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column EB_CAT.CAT_TYPE
	 * 
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	private Integer catType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.CAT_ID
	 * 
	 * @return the value of EB_CAT.CAT_ID
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public Long getCatId() {
		return catId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.CAT_ID
	 * 
	 * @param catId
	 *            the value for EB_CAT.CAT_ID
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setCatId(Long catId) {
		this.catId = catId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.CAT_NAME
	 * 
	 * @return the value of EB_CAT.CAT_NAME
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getCatName() {
		return catName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.CAT_NAME
	 * 
	 * @param catName
	 *            the value for EB_CAT.CAT_NAME
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setCatName(String catName) {
		this.catName = catName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.CAT_DESC
	 * 
	 * @return the value of EB_CAT.CAT_DESC
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getCatDesc() {
		return catDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.CAT_DESC
	 * 
	 * @param catDesc
	 *            the value for EB_CAT.CAT_DESC
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setCatDesc(String catDesc) {
		this.catDesc = catDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.PARENT_ID
	 * 
	 * @return the value of EB_CAT.PARENT_ID
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.PARENT_ID
	 * 
	 * @param parentId
	 *            the value for EB_CAT.PARENT_ID
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.CAT_SORT
	 * 
	 * @return the value of EB_CAT.CAT_SORT
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public Integer getCatSort() {
		return catSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.CAT_SORT
	 * 
	 * @param catSort
	 *            the value for EB_CAT.CAT_SORT
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setCatSort(Integer catSort) {
		this.catSort = catSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.KEYWORDS
	 * 
	 * @return the value of EB_CAT.KEYWORDS
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.KEYWORDS
	 * 
	 * @param keywords
	 *            the value for EB_CAT.KEYWORDS
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.PATH
	 * 
	 * @return the value of EB_CAT.PATH
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.PATH
	 * 
	 * @param path
	 *            the value for EB_CAT.PATH
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.MARK
	 * 
	 * @return the value of EB_CAT.MARK
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.MARK
	 * 
	 * @param mark
	 *            the value for EB_CAT.MARK
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setMark(String mark) {
		this.mark = mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.ISDISPLAY
	 * 
	 * @return the value of EB_CAT.ISDISPLAY
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public Integer getIsdisplay() {
		return isdisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.ISDISPLAY
	 * 
	 * @param isdisplay
	 *            the value for EB_CAT.ISDISPLAY
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setIsdisplay(Integer isdisplay) {
		this.isdisplay = isdisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.FULL_PATH
	 * 
	 * @return the value of EB_CAT.FULL_PATH
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public String getFullPath() {
		return fullPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.FULL_PATH
	 * 
	 * @param fullPath
	 *            the value for EB_CAT.FULL_PATH
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setFullPath(String fullPath) {
		this.fullPath = fullPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column EB_CAT.CAT_TYPE
	 * 
	 * @return the value of EB_CAT.CAT_TYPE
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public Integer getCatType() {
		return catType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column EB_CAT.CAT_TYPE
	 * 
	 * @param catType
	 *            the value for EB_CAT.CAT_TYPE
	 * @mbggenerated Mon Jul 27 17:23:56 CST 2015
	 */
	public void setCatType(Integer catType) {
		this.catType = catType;
	}

	@Override
	public String toString() {
		return "EbCat [catId=" + catId + ", catName=" + catName + ", catDesc="
				+ catDesc + ", parentId=" + parentId + ", catSort=" + catSort
				+ ", keywords=" + keywords + ", path=" + path + ", mark="
				+ mark + ", isdisplay=" + isdisplay + ", fullPath=" + fullPath
				+ ", catType=" + catType + "]";
	}

}