package com.worthto.ecps.model;

public class EbItemClob {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_ITEM_CLOB.ITEM_ID
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	private Long itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_ITEM_CLOB.ITEM_DESC
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	private String itemDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EB_ITEM_CLOB.PACKING_LIST
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	private String packingList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_ITEM_CLOB.ITEM_ID
	 * @return  the value of EB_ITEM_CLOB.ITEM_ID
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public Long getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_ITEM_CLOB.ITEM_ID
	 * @param itemId  the value for EB_ITEM_CLOB.ITEM_ID
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_ITEM_CLOB.ITEM_DESC
	 * @return  the value of EB_ITEM_CLOB.ITEM_DESC
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_ITEM_CLOB.ITEM_DESC
	 * @param itemDesc  the value for EB_ITEM_CLOB.ITEM_DESC
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EB_ITEM_CLOB.PACKING_LIST
	 * @return  the value of EB_ITEM_CLOB.PACKING_LIST
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public String getPackingList() {
		return packingList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EB_ITEM_CLOB.PACKING_LIST
	 * @param packingList  the value for EB_ITEM_CLOB.PACKING_LIST
	 * @mbggenerated  Tue Jul 28 17:30:11 CST 2015
	 */
	public void setPackingList(String packingList) {
		this.packingList = packingList;
	}
}